version: '3.8'

services:
  meu-postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./load_data_clientes.sql:/docker-entrypoint-initdb.d/load_data_clientes.sql
      - ./load_data_servicos.sql:/docker-entrypoint-initdb.d/load_data_servicos.sql
      - ./load_data_quartos.sql:/docker-entrypoint-initdb.d/load_data_quartos.sql
      - ./load_data_reservas.sql:/docker-entrypoint-initdb.d/load_data_reservas.sql
    ports:
      - "5432:5432"
    networks:
      - my_network

  ms-clientes:
    container_name: ms-clientes
    build:
      context: ./ms-clientes 
      dockerfile: Dockerfile
    environment:
      PG_HOST: jdbc:postgresql://meu-postgres:5432/clientes
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - meu-postgres
    networks:
      - my_network

  ms-servicos-opcionais:
    container_name: ms-servicos-opcionais
    build:
      context: ./ms-servicos-opcionais 
      dockerfile: Dockerfile
    environment:
      PG_HOST: jdbc:postgresql://meu-postgres:5432/servicos_opcionais
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - meu-postgres
    networks:
      - my_network

  ms-quartos:
    container_name: ms-quartos
    build:
      context: ./ms-quartos 
      dockerfile: Dockerfile
    environment:
      PG_HOST: jdbc:postgresql://meu-postgres:5432/quartos
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - meu-postgres
    networks:
      - my_network
    ports:
      - 8083:8083

networks:
  my_network: