version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clientes,itens
    command: >
      bash -c '
        echo "CREATE DATABASE clientes;" >> /docker-entrypoint-initdb.d/init.sql &&
        echo "CREATE DATABASE itens;" >> /docker-entrypoint-initdb.d/init.sql &&
        docker-entrypoint.sh postgres
      ' 
    ports:
      - "5432:5432"