version: '3.8'

services:
  meu-postgres:
    image: postgres:15.6
    container_name: meu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./load_data_clientes.sql:/docker-entrypoint-initdb.d/load_data_clientes.sql
      - ./load_data_servicos.sql:/docker-entrypoint-initdb.d/load_data_servicos.sql
      - ./load_data_quartos.sql:/docker-entrypoint-initdb.d/load_data_quartos.sql
      - ./load_data_reservas.sql:/docker-entrypoint-initdb.d/load_data_reservas.sql
    ports:
      - "5432:5432"
    networks:
      - my_network

  ms-clientes:
    container_name: ms-clientes
    build:
      context: ./ms-clientes 
      dockerfile: Dockerfile
    environment:
      PG_HOST: jdbc:postgresql://meu-postgres:5432/clientes
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - meu-postgres
    networks:
      - my_network

  ms-servicos-opcionais:
    container_name: ms-servicos-opcionais
    build:
      context: ./ms-servicos-opcionais 
      dockerfile: Dockerfile
    environment:
      PG_HOST: jdbc:postgresql://meu-postgres:5432/servicos_opcionais
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - meu-postgres
    networks:
      - my_network

  ms-quartos:
    container_name: ms-quartos
    build:
      context: ./ms-quartos 
      dockerfile: Dockerfile
    environment:
      PG_HOST: jdbc:postgresql://meu-postgres:5432/quartos
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - meu-postgres
    networks:
      - my_network
      
  ms-reservas:
    container_name: ms-reservas
    build:
      context: ./ms-reservas
      dockerfile: Dockerfile
    environment:
      PG_HOST: jdbc:postgresql://meu-postgres:5432/reservas
      PG_USER: postgres
      PG_PASSWORD: postgres
      MS_EMAIL: ms-email
      MS_CLIENTES: ms-clientes
      MS_SERVICOS: ms-servicos-opcionais
      MS_QUARTOS: ms-quartos
    depends_on:
      - meu-postgres
      - ms-email
      - ms-clientes
      - ms-servicos-opcionais
      - ms-quartos
    networks:
      - my_network

  ms-email:
    container_name: ms-email
    build:
      context: ./ms-email 
      dockerfile: Dockerfile
    environment:
      SPRING_MAIL_PASS: "sua key aqui"
    networks:
      - my_network

  ms-gateway:
    container_name: ms-gateway
    build:
      context: ./ms-gateway 
      dockerfile: Dockerfile
    environment:
      HOST_SERVICOS: http://ms-servicos-opcionais:8082/ms-servicos
      HOST_RESERVAS: http://ms-reservas:8084/ms-reservas
      HOST_QUARTOS: http://ms-quartos:8083/ms-quartos
      HOST_CLIENTES: http://ms-clientes:8081/ms-cliente
    networks:
      - my_network
    depends_on:
      - meu-postgres
      - ms-email
      - ms-clientes
      - ms-servicos-opcionais
      - ms-quartos
    ports:
      - 8080:8080

networks:
  my_network: