version: '3.8'

services:
  meu-postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clientes,servicos_opcionais
    volumes:
      - ./load_data_clientes.sql:/docker-entrypoint-initdb.d/load_data_clientes.sql
    ports:
      - "5432:5432"
    networks:
      - my_network

  ms-clientes:
    container_name: ms-clientes
    build:
      context: ./ms-clientes 
      dockerfile: Dockerfile
    environment:
      PG_HOST: jdbc:postgresql://meu-postgres:5432/clientes
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - meu-postgres
    networks:
      - my_network

networks:
  my_network: